replicaCount: 3

image:
  repository: inventory
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

resources: {}

nodeSelector: {}

tolerations: []

serviceAccount: {}

autoscaling: { enabled: false}

affinity: {}
